npm/policies

conduct.md
disputes.md
dmca.md
receiving-reports.md
recruiting-process.md

Note: Some are quite nitpicky, or even border on being unnecessary: cherry-pick whatever is deemed useful!
British to American:
* `behaviour` > `behavior`;
* `apologise` > `apologize`;
* `judgement` > `judgment` (see http://grammarist.com/spelling/judgment-judgement/).
Casing:
* `erlang` > `Erlang`;
* `english` > `English`.
Miscellaneous:
* `ie` > `i.e.`;
* `notifice` > `notice`;
* `spiralling` > `spiraling` (this is a bit more vague,
some spellcheckers highlight it, wikitionary
mentions it too: https://en.wiktionary.org/wiki/spiral#Verb).

Fix several typographic errors

---

open-source-terms.md
private-modules-terms.md
terms.md

This PR adds:
1.  terms of use for npm Open Source
2.  additional terms of use for npm Personal, a/k/a Private Modules
3.  an index page, called "terms", that links to those new terms, plus
CLI's license file
The npm Personal terms currently link to
<https://www.npmjs.com/private-modules> for a description of npm
Personal features. That may need to be updated once npmjs.com has new
pages describing Orgs and other offerings.

Add npm Open Source and npm Personal terms of use

---

.gitignore
.travis.yml
Gemfile
Makefile
disputes.md
open-source-terms.md
package.json
recruiting-process.md

This small PR replaces #26.
It:
1. Configures Travis CI to check policy files, rendered with marked via revised `Makefile`, for broken hyperlinks with html-proofer.
2. Fixes a few broken hyperlinks.

Use tools to check hyperlinks

---

privacy.md

In partial response to #31.
This PR changes the e-mail address for privacy-related e-mail to legal@npmjs.com, which is now verified working.

Use legal@npmjs.com for privacy mail, too

---

open-source-terms.md
organization-plan.md
personal-plan.md
private-terms.md

Responsive to #30, with very special thanks to @rmg
This PR refines the terms for npm Open-Source that grant npm, Inc. the license it needs to publish user content. Its purpose is to clarify our original intent: To make explicit the permission users give npm to make their content available to other users.
As a legal drafting task, this is a bit tricky, in that npm, Inc. makes lots of copies, sends them to lots of people, and also needs rights to inspect and process the contents of code packages, say to check bundledDependencies. In the future, as npm does more on the registry and website to improve install speed and package discovery, we may need to revisit this language again.
For now, however, we've had great feedback on perceived overbreadth in the opposite direction: Folks are …

Clarify user content license

---

open-source-terms.md

This small PR clarifies the language about npm's license to share content that folks share via npm.

Clarify npm's license to share content

---

security.md

Since we are officially un-re-branding. This will propagate to https://docs.npmjs.com/policies/security.

docs(security): update On-Site product name to Enterprise

---

organization-plan.md

The link in the orgs payment plan doc pointed to the history of the _personal_ payment plan.

Fix link to past versions of Orgs payment plan

---

domains.md

Remove second appearance of npm.tips domain from the Idle domains list.

Remove duplicated entry from the Idle domains list

---

disputes.md

This small PR clarifies language in the "Trademarks" section of our disputes policy, to clarify how we will handle trademark-based disputes about usernames and org names, in addition to package names.

Clarify trademark-based dispute procedures for user-name and org-scope disputes

---

private-terms.md
trademark.md

This PR removes tab characters from Markdown files, both for consistency, and to avoid rendering break tags in paragraphs where the tabs appeared at the ends of plain-text lines.

Remove Tab Characters

---

organization-plan.md
personal-plan.md

@seldo, this small patch adds parallel reminders to our Orgs and Personal payments plans that accounts belong to single users, and every person using paid services needs an account under a payment plan.
I've updated the dates on the payment plans, but these changes shouldn't affect the meaning of the terms.  The only additions are pointers back to other terms, from which customers should already understand they need _n_ accounts in an org for _n_ people, and can't share a Personal Plan by sharing credentials.

terms: Add notes reminding not to share paid accounts

---

open-source-terms.md
privacy.md
terms.md

This WIP PR revises the privacy policy and Open Source terms to cover and address [npm.community](https://npm.community).  I will need to take at least one more pass.
cc @zkat, @iarna

Address npm.community

---

unpublish.md

Updates the republish time window to 24 hours. (It was incorrectly changed to 72 hours.)

Fix republish time window

---

privacy.md

This PR updates parts of our privacy policy to reflect our transition from Smyte to Sift Science for automated spam and abuse prevention.

Smyte -> Sift

---

open-source-terms.md

This pull request adds a new Commercial Content section to further clarify our approach to advertisements, sponsorships, and various ways of communicating through the npm public registry, website, and command-line interface.

Open Source: Add Commercial Content section

---

dmca.md
open-source-terms.md
privacy.md

The mailing address on our dmca, privacy policy, and open source terms pages is out of date.
(It's our old Oakland office.)
https://npm-inc.slack.com/archives/C025CG2D2/p1588091003053700

Update npm mailing address

---

README.md
dmca.md
open-source-terms.md
privacy.md

Update the physical addresses for contacting us in all our policy documentation.  In each case, the legal and privacy contacts are now GitHub, Inc.

Update contact information

---

business-solution-terms.md
conduct.md
disputes.md
npm-license.md
open-source-terms.md
privacy.md
receiving-reports.md
security.md
unpublish.md

npm now has a single point of entry for receiving support requests:
https://npmjs.com/support.  npm no longer accepts new support tickets
via email.
By having a single point of entry into our support channel, we can
provide more efficient support.  In particular, by using a form on the
website, we can gather additional information up-front, to respond to
support requests more quickly.
The policy documents are updated to reflect the new mechanism for
contacting support.  This is a change to the mechanisms of contacting
support, and not a change to the way in which you report problems or
receive support.

Update support contact to be the new support website

---

package-lock.json
package.json

Looks like this was accidentally switched from `@npm/mkp` to `mkp` when we moved the internal packages to GPR in #142

Use correct version of mkp package

---

privacy.md

npm no longer uses tracking cookies; remove the information about them.

privacy: we do not use tracking cookies

---

README.md

Reverts npm/policies#147
These pages are built for our website and checked in to this repository for visibility and traceability. But that means that the links are formatted for our website at https://www.npmjs.com/policies. Changing them so that they're useful in the context of this repository - at the moment - breaks the links on our website.
Obviously it would be nice if they were consistent and usable in both places, but the tooling does not do this at the moment. I'm reverting this to fix the website.

Revert "Fixed all the broken links in README.md"

---

security.md

Security support tickets now should come through https://npmjs.com/support - which allows us to collect more information about the tickets to route them to the correct team as quickly as possible.

security: updates for new security support tickets

---

conduct.md

This email address is no longer how to report vulnerabilities

conduct: remove reference to security@npmjs.com

---

README.md

policies now live at https://github.com/npm/documentation/tree/main/content/policies

docs: archive repostiory
