trademark.md

trademark: Protect the wombat from misuse/abuse

---

conduct.md
privacy.md

This tiny PR updates npm, Inc.'s office address in its code of conduct and privacy policy.

Update npm, Inc. office address

---

conduct.md

https://www.rust-lang.org/conduct.html

Add link to new home of Rust's CoC

---

open-source-terms.md

Prohibit trade in reserved names

---

private-modules-terms.md

Fix Private Modules payment cycle description

---

privacy.md

Fixes link to Oracle Marketing Cloud privacy policy and corrects typo

Fix Oracle Marketing Cloud paragraph

---

conduct.md

upstreaming a good change that came from a contributor to node/inclusivity: https://github.com/nodejs/inclusivity/pull/22#discussion_r45375043

substitute ability for disability

---

README.md
security.md

Re: https://github.com/npm/issue-tracker/issues/415
Copy changes at https://github.com/npm/internal-docs/pull/39

Add security policy

---

disputes.md
trademark.md

This PR adds a new section to the dispute resolution policy about disputes related to trademarks.
cc @seldo

Add special steps for trademark disputes

---

enterprise-terms.md

terms: Add npm Enterprise Self-Serve License Terms

---

enterprise-terms.md

cc @seldo @aredridel @cowperthwait @bcoe

npm Enterprise Terms 6.0.0

---

README.md
domains.md

Somebody got sketched out by seeing an npm.im link and suggested we attest that it really belongs to us.

List of domains

---

dmca.md

This pull request replaces the current DMCA policy with the new one @seldo and I have prepared and reviewed.

DMCA: Clarify and expand DMCA policy

---

enterprise-terms.md

Fixed a typo in in payment obligations terms.

npm Enterprise Terms 6.0.1

---

security.md

Now including ceejbot as well as seldo.

update security point of contact information

---

security.md

 updates link to Ubuntu security notices

---

privacy.md

@cowperthwait, we can land and publish this update immediately.  Our new terms mention that we will update contact information in place, without mentioning on the blog.

privacy: Update EU representative contact info

---

privacy.md

With thanks to @jboavida.
@cowperthwait, we can deploy this without notice or other announcement. It's just a link HREF fix.
I'll merge myself.

privacy: Fix Fastly link

---

privacy.md

Pulling back Privacy Shield participation language, pending final approval DOC.

Revert privacy shield language

---

privacy.md

privacy: Mention Slack and link to their privacy policy

---

organization-plan.md

terms: Fix markup error

---

private-terms.md

terms: Fix capitalization of Payment Terms heading

---

security.md

Covers
* New internal security team
* New points of contact
* Inclusion of Google Cloud
Explicitly still in need of update:
* Logging changes
* Password and auth changes
* Dev process changes

Partial update of security policies

---

open-source-terms.md

Relatively minor stylistic and typographic fixes.  Sending this pull request to remind myself to land them with our next substantive updates.

Open Source Terms Proofreading Pass

---

DEVELOPING.txt

Add bare-bones instructions for "what to do if filenames change." (TL;DR: ping me and I will make sure they get out.) Added a timestamp because we want this situation to be temporary. Added it as a `.txt` file because otherwise it'd get built and shipped with the rest of the policy pages.

add DEVELOPING.txt

---

open-source-terms.md

Adapt security data conditions from NSP terms

---

disputes.md

Updates the user name dispute steps to match the organization name dispute steps /cc @elizabethalk

Update user name dispute steps

---

business-solution-terms.md

Business Solution Terms: Make URLs links

---

DEVELOPING.txt

- Adds a section header for "Creating new files or renaming existing files" info
- Adds steps for deploying to staging and production

fix: update steps for creating and renaming files and deploying

---

privacy.md

New section for HubSpot, describing how we use it, and linking to their privacy policy.

privacy: Add HubSpot

---

private-terms.md

Update npm Paid Services documentation URL

---

privacy.md

This PR adds a new section to our privacy questions and answers addressing the California Consumer Privacy Act.

Privacy: Address CCPA

---

package-lock.json
privacy.md

policy updates

---

.npmrc
package-lock.json
package.json

Changes to package-lock.json and .npmrc, following the issue: https://github.com/github/npm/issues/1748

Migrating to GH packages

---

conduct.md
disputes.md
receiving-reports.md
security.md

I reviewed existing policies and checked documented emails to make sure we were properly directing folks to the right place. Updated documentation accordingly.
This change is purely editorial and does not modify any of the policies themselves.

Update contact info

---

README.md

All the links in the README.md file were pointing to incorrect urls.

Fixed all the broken links in README.md

---

privacy.md

Our support team is available to help with privacy requests by opening a
ticket at https://npmjs.com/support.

privacy: update contact information
